import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Weekly NWA Briefings",
  description:
    "Jamie Allison's weekly briefing on venture, AI, markets, and the angel-investing curriculum.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-white text-slate-900">
        <header className="bg-[#0a1628] text-white">
          <div className="max-w-3xl mx-auto px-5 py-6 flex items-center justify-between">
            <Link href="/" className="flex flex-col">
              <span className="text-lg font-bold tracking-tight">
                Weekly NWA Briefings
              </span>
              <span className="text-xs opacity-70">Jamie Allison</span>
            </Link>
            <nav className="flex items-center gap-5 text-sm">
              <Link href="/" className="hover:opacity-80">
                Briefings
              </Link>
              <Link href="/learning" className="hover:opacity-80">
                Learning
              </Link>
            </nav>
          </div>
        </header>
        <main className="flex-1">{children}</main>
        <footer className="border-t border-slate-200 mt-12">
          <div className="max-w-3xl mx-auto px-5 py-6 text-xs text-slate-500">
            Generated by Claude CoWork · weekly cadence (Sundays, 6:00 PM ET)
          </div>
        </footer>
      </body>
    </html>
  );
}
